from enum import Enum


class InterviewState(str, Enum):
    INTRO = "INTRO"
    AWAITING_CLARIFICATION = "AWAITING_CLARIFICATION"
    AWAITING_APPROACH = "AWAITING_APPROACH"
    AWAITING_CODE = "AWAITING_CODE"
    AWAITING_WALKTHROUGH = "AWAITING_WALKTHROUGH"
    CONCLUDING = "CONCLUDING"
    GENERATING_DEBRIEF = "GENERATING_DEBRIEF"
    COMPLETED = "COMPLETED"
